# valores recomendados de resolucion para mantener la relacion: 
# (ancho, alto): 640x480, 800x600, 960x720, 1024x768
ancho_ventana: 960
alto_ventana: 720
fullscreen: false ## false -> Dimension fija, true -> Fullscreen
fps: 30