#ifndef PREFIJOS_PROTOCOLO_H
#define PREFIJOS_PROTOCOLO_H

#define PREFIJO_MOVIMIENTO 0x01
#define PREFIJO_DISPARAR 0x02
#define PREFIJO_ROTACION 0x03
#define PREFIJO_CAMBIO_ARMA 0x04
#define PREFIJO_COMPRAR 0x05
#define PREFIJO_SELECCIONAR_SKIN 0x06
#define PREFIJO_CREAR_PARTIDA 0x0A
#define PREFIJO_UNIRSE_PARTIDA 0x0B
#define PREFIJO_LISTAR 0x0C
#define CMD_EXIT 0x12


#endif